sudo: required
notifications:
  email: false
language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "8"
cache:
  directories:
  - home/travis/build/jarifibrahim/fabric8-planner/node_modules
  - home/travis/build/jarifibrahim/fabric8-planner/runtime/node_modules
install:
 - npm install
 - npm run build
 - cd runtime
 - npm install
script:
 - HEADLESS_MODE=true npm run test:funcsmoke