language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "8"
install:
 - npm install
 - npm run build
 - cd runtime
 - npm install
script:
 - npm run test:funcsmoke