sudo: required
notifications:
  email: false
language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "8"
install:
 - npm install codecov -g
 - npm install
#  - npm run build
#  - cd runtime
#  - npm install
script:
#  - HEADLESS_MODE=true npm run test:funcsmoke
  - npm run test:unit
after_success:
  - codecov
